# Generated by Django 4.1.2 on 2022-11-05 17:05

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentdata',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
