# Generated by Django 4.1.2 on 2022-11-05 17:08

from django.db import migrations
import voting.manager


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_studentdata_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentdata',
            managers=[
                ('objects', voting.manager.UserManager()),
            ],
        ),
    ]
