# Generated by Django 4.1.2 on 2022-11-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_studentdata_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='voted',
            field=models.CharField(default='no', max_length=12),
        ),
    ]
